name: Quick Verify Secrets

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Quick Check Secrets
        run: |
          echo "Checking GitHub Secrets..."
          
          # Check VERCEL_TOKEN
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✅ VERCEL_TOKEN exists"
          else
            echo "❌ VERCEL_TOKEN is missing"
          fi
          
          # Check VERCEL_ORG_ID
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✅ VERCEL_ORG_ID exists"
          else
            echo "❌ VERCEL_ORG_ID is missing"
          fi
          
          # Check VERCEL_PROJECT_ID
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "✅ VERCEL_PROJECT_ID exists"
          else
            echo "❌ VERCEL_PROJECT_ID is missing"
          fi 