name: Verify Vercel Secrets

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Vercel Token
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✅ VERCEL_TOKEN is set"
          else
            echo "❌ VERCEL_TOKEN is not set"
            exit 1
          fi

      - name: Check Vercel Org ID
        run: |
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✅ VERCEL_ORG_ID is set"
          else
            echo "❌ VERCEL_ORG_ID is not set"
            exit 1
          fi

      - name: Check Vercel Project ID
        run: |
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "✅ VERCEL_PROJECT_ID is set"
          else
            echo "❌ VERCEL_PROJECT_ID is not set"
            exit 1
          fi

      - name: Verify Vercel Connection
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} project ls
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 