name: Verify Vercel Secrets

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Debug Secrets (without exposing values)
        run: |
          echo "Checking if secrets are set..."
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "❌ VERCEL_TOKEN is not set"
          else
            echo "✅ VERCEL_TOKEN is set (length: ${#VERCEL_TOKEN})"
          fi
          
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "❌ VERCEL_ORG_ID is not set"
          else
            echo "✅ VERCEL_ORG_ID is set (length: ${#VERCEL_ORG_ID})"
          fi
          
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "❌ VERCEL_PROJECT_ID is not set"
          else
            echo "✅ VERCEL_PROJECT_ID is set (length: ${#VERCEL_PROJECT_ID})"
          fi

      - name: Verify Vercel Connection
        run: |
          echo "Attempting to connect to Vercel..."
          vercel --token ${{ secrets.VERCEL_TOKEN }} project ls --debug
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        continue-on-error: true

      - name: Check Project Status
        if: always()
        run: |
          echo "Checking project status..."
          vercel --token ${{ secrets.VERCEL_TOKEN }} project ls
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        continue-on-error: true 